# Generated by Django 4.1.7 on 2023-04-27 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('author', models.CharField(blank=True, max_length=64)),
                ('genre', models.CharField(blank=True, max_length=64)),
                ('length', models.IntegerField()),
                ('publisher', models.CharField(blank=True, max_length=64)),
                ('users', models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
